/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        boton_Home = new javax.swing.JPanel();
        boton_home = new javax.swing.JLabel();
        boton_A01 = new javax.swing.JPanel();
        boton_home1 = new javax.swing.JLabel();
        boton_A2 = new javax.swing.JPanel();
        boton_home2 = new javax.swing.JLabel();
        boton_A3 = new javax.swing.JPanel();
        boton_home3 = new javax.swing.JLabel();
        boton_A4 = new javax.swing.JPanel();
        boton_home4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        bg.setForeground(new java.awt.Color(0, 51, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 102, 153));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Home.setBackground(new java.awt.Color(0, 153, 204));
        boton_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_Home.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        boton_home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boton_home.setText("Home");
        boton_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_homeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout boton_HomeLayout = new javax.swing.GroupLayout(boton_Home);
        boton_Home.setLayout(boton_HomeLayout);
        boton_HomeLayout.setHorizontalGroup(
            boton_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_HomeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(boton_home, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        boton_HomeLayout.setVerticalGroup(
            boton_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_HomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_home)
                .addGap(20, 20, 20))
        );

        sidePanel.add(boton_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 50));

        boton_A01.setBackground(new java.awt.Color(0, 153, 255));
        boton_A01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_A01.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boton_A01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_A01MousePressed(evt);
            }
        });

        boton_home1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boton_home1.setText("A_01");

        javax.swing.GroupLayout boton_A01Layout = new javax.swing.GroupLayout(boton_A01);
        boton_A01.setLayout(boton_A01Layout);
        boton_A01Layout.setHorizontalGroup(
            boton_A01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_A01Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(boton_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        boton_A01Layout.setVerticalGroup(
            boton_A01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_A01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_home1)
                .addGap(20, 20, 20))
        );

        sidePanel.add(boton_A01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 50));

        boton_A2.setBackground(new java.awt.Color(0, 153, 255));
        boton_A2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_A2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boton_A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_A2MousePressed(evt);
            }
        });

        boton_home2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boton_home2.setText("A_02");

        javax.swing.GroupLayout boton_A2Layout = new javax.swing.GroupLayout(boton_A2);
        boton_A2.setLayout(boton_A2Layout);
        boton_A2Layout.setHorizontalGroup(
            boton_A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_A2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(boton_home2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        boton_A2Layout.setVerticalGroup(
            boton_A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_A2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_home2)
                .addGap(20, 20, 20))
        );

        sidePanel.add(boton_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        boton_A3.setBackground(new java.awt.Color(0, 153, 255));
        boton_A3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_A3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        boton_home3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boton_home3.setText("A_03");

        javax.swing.GroupLayout boton_A3Layout = new javax.swing.GroupLayout(boton_A3);
        boton_A3.setLayout(boton_A3Layout);
        boton_A3Layout.setHorizontalGroup(
            boton_A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_A3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(boton_home3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        boton_A3Layout.setVerticalGroup(
            boton_A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_A3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_home3)
                .addGap(20, 20, 20))
        );

        sidePanel.add(boton_A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 50));

        boton_A4.setBackground(new java.awt.Color(0, 153, 255));
        boton_A4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton_A4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        boton_home4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boton_home4.setText("A_04");

        javax.swing.GroupLayout boton_A4Layout = new javax.swing.GroupLayout(boton_A4);
        boton_A4.setLayout(boton_A4Layout);
        boton_A4Layout.setHorizontalGroup(
            boton_A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_A4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(boton_home4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        boton_A4Layout.setVerticalGroup(
            boton_A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boton_A4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_home4)
                .addGap(72, 72, 72))
        );

        sidePanel.add(boton_A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Gfacturas");
        sidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 10));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 453));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("historial_______________________");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Administracion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 31, 680, 100));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 670, 200));
        bg.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 260, 30));
        bg.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 260, 30));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
       System.exit(0);
    }//GEN-LAST:event_jLabel4MousePressed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void boton_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_homeMousePressed
        setColor(boton_Home);
        resetColor(boton_A01);
        resetColor(boton_A2);
    }//GEN-LAST:event_boton_homeMousePressed

    private void boton_A01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_A01MousePressed
         setColor(boton_A01);
        resetColor(boton_Home);
        resetColor(boton_A2);
    }//GEN-LAST:event_boton_A01MousePressed

    private void boton_A2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_A2MousePressed
        setColor(boton_A2);
        resetColor(boton_A01);
        resetColor(boton_Home);
    }//GEN-LAST:event_boton_A2MousePressed
    void setColor(JPanel panel){
        
        panel.setBackground(new Color(204,204,204));
    }
    void resetColor (JPanel panel){
        panel.setBackground(new Color(153,153,153));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel boton_A01;
    private javax.swing.JPanel boton_A2;
    private javax.swing.JPanel boton_A3;
    private javax.swing.JPanel boton_A4;
    private javax.swing.JPanel boton_Home;
    private javax.swing.JLabel boton_home;
    private javax.swing.JLabel boton_home1;
    private javax.swing.JLabel boton_home2;
    private javax.swing.JLabel boton_home3;
    private javax.swing.JLabel boton_home4;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
