/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.gfacturas.vista;

import com.software.gfacturas.controlador.ControllerUsu;
import com.software.gfacturas.modelo.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Castro
 */
public class Registro extends javax.swing.JFrame {
    ControllerUsu controller;
    /**
     * Creates new form login
     */
    public Registro() {
        controller = new ControllerUsu();
        initComponents();
        setLocationRelativeTo(null);
        setTitle("gFactura Registro");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtPContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtPContraseña2 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/avatar.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 200, 190));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Medium", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GFacturas");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 120, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Registro");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/city.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 200, 500));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuario");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 300, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingresar su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtPContraseña.setBackground(new java.awt.Color(255, 255, 255));
        txtPContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtPContraseña.setText("********");
        txtPContraseña.setToolTipText("");
        txtPContraseña.setBorder(null);
        txtPContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPContraseñaMousePressed(evt);
            }
        });
        bg.add(txtPContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 300, 20));

        btnLogin.setBackground(new java.awt.Color(78, 184, 222));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre Completo");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 20));

        txtNombreC.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreC.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreC.setText("Ingresar su nombre completo");
        txtNombreC.setBorder(null);
        txtNombreC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreCMousePressed(evt);
            }
        });
        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });
        bg.add(txtNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, -1));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 10));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Confirmar Contraseña");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtPContraseña2.setBackground(new java.awt.Color(255, 255, 255));
        txtPContraseña2.setForeground(new java.awt.Color(204, 204, 204));
        txtPContraseña2.setText("********");
        txtPContraseña2.setBorder(null);
        txtPContraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPContraseña2MousePressed(evt);
            }
        });
        bg.add(txtPContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, -1));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 300, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Volver");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        //btnEntrar.setBackground(new Color(0,156,223));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
        // btnEntrar.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnRegistrar.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnLoginMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (txtUsuario.getText().equals("Ingresar su nombre de usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(txtPContraseña.getPassword()).isEmpty()) {
            txtPContraseña.setText("********");
            txtPContraseña.setForeground(Color.gray);
        }
        if(txtNombreC.getText().isEmpty()){
            txtNombreC.setText("Ingresar su nombre completo");
            txtNombreC.setForeground(Color.gray);
        }
        if (String.valueOf(txtPContraseña2.getPassword()).isEmpty()) {
            txtPContraseña2.setText("********");
            txtPContraseña2.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPContraseñaMousePressed
        if (String.valueOf(txtPContraseña.getPassword()).equals("********")) {
            txtPContraseña.setText("");
            txtPContraseña.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingresar su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
        if(txtNombreC.getText().isEmpty()){
            txtNombreC.setText("Ingresar su nombre completo");
            txtNombreC.setForeground(Color.gray);
        }
        if (String.valueOf(txtPContraseña2.getPassword()).isEmpty()) {
            txtPContraseña2.setText("********");
            txtPContraseña2.setForeground(Color.gray);
        }
        

    }//GEN-LAST:event_txtPContraseñaMousePressed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        accion();
    }//GEN-LAST:event_btnRegistrarMouseClicked
    
    public void accion(){
        boolean v = false;
        if(!String.valueOf(txtPContraseña.getPassword()).equals(String.valueOf(txtPContraseña2.getPassword()))){
            JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales","Error Registro",JOptionPane.ERROR_MESSAGE);
            v = true;
        }
        if(txtNombreC.getText().equals("Ingresar su nombre completo") || txtUsuario.getText().equals("Ingresar su nombre de usuario") || String.valueOf(txtPContraseña.getPassword()).equals("********") || String.valueOf(txtPContraseña2.getPassword()).equals("********")){
            JOptionPane.showMessageDialog(null, "No debe quedar ningun campo vacio","Error Registro",JOptionPane.ERROR_MESSAGE);
            v = true;
        }
        if(controller.existe(txtUsuario.getText())){
            JOptionPane.showMessageDialog(null, "No se puede realizar el registro, debido a que el usuario ya existe ","Error Registro",JOptionPane.ERROR_MESSAGE);
            v = true;
        }
        if(!v){
            if(controller.registro(new Usuario(txtNombreC.getText(),txtUsuario.getText(),String.valueOf(txtPContraseña.getPassword())))){
                JOptionPane.showMessageDialog(null, "Registro exitoso","registro",JOptionPane.INFORMATION_MESSAGE);
                lMouseCli();
            }else{
                JOptionPane.showMessageDialog(null, "Registro rechazado","Error registro",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed

    private void txtNombreCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCMousePressed
        // TODO add your handling code here:
        if(txtNombreC.getText().equals("Ingresar su nombre completo")){
            txtNombreC.setText("");
            txtNombreC.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingresar su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
        if (String.valueOf(txtPContraseña2.getPassword()).isEmpty()) {
            txtPContraseña2.setText("********");
            txtPContraseña2.setForeground(Color.gray);
        }
        if (String.valueOf(txtPContraseña.getPassword()).isEmpty()) {
            txtPContraseña.setText("********");
            txtPContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreCMousePressed

    private void txtPContraseña2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPContraseña2MousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtPContraseña2.getPassword()).equals("********")) {
            txtPContraseña2.setText("");
            txtPContraseña2.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Ingresar su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
        if(txtNombreC.getText().isEmpty()){
            txtNombreC.setText("Ingresar su nombre completo");
            txtNombreC.setForeground(Color.gray);
        }
        if (String.valueOf(txtPContraseña.getPassword()).isEmpty()) {
            txtPContraseña.setText("********");
            txtPContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPContraseña2MousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        lMouseCli();
    }//GEN-LAST:event_jLabel9MouseClicked
    public void lMouseCli(){
        login l = new login();
        this.setVisible(false);
        l.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JPasswordField txtPContraseña;
    private javax.swing.JPasswordField txtPContraseña2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
